name: Build Android APK
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
      - uses: gradle/actions/setup-gradle@v3
        with: { gradle-version: 8.7 }
      - name: Build release APK
        working-directory: android
        run: gradle :app:assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: TornadoAI-APK
          path: android/app/build/outputs/apk/release/*.apk
