name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ env.PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK (cmdline-tools)
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"/cmdline-tools
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT"/cmdline-tools
          mv "$ANDROID_SDK_ROOT"/cmdline-tools/cmdline-tools "$ANDROID_SDK_ROOT"/cmdline-tools/latest
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # ⬇️ If your Android project lives in ./android, keep this working-directory
      #    If it’s at repo root, remove 'working-directory' lines below.
      - name: Make gradlew executable
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build release APK
        working-directory: android
        run: ./gradlew :app:assembleRelease --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: TornadoAI-APK
          path: android/app/build/outputs/apk/release/*.apk